chore: moving to PyYAML==6.0.1
the 6.0 causes:

```
AttributeError: cython_sources
```

see:
https://northern-tech.slack.com/archives/C0XM0KX9C/p1689652088065289
https://northern-tech.slack.com/archives/C0XM0KX9C/p1689667137865079


Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>